# Generated by Django 4.1.7 on 2023-03-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, null=True, verbose_name='Имя')),
                ('birthdate', models.DateField(null=True, verbose_name='Год рождения')),
                ('password', models.CharField(max_length=10000, null=True, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=10000, null=True, verbose_name='Почта')),
                ('profile_picture', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'db_table': 'accounts',
                'managed': False,
            },
        ),
    ]
