# Generated by Django 4.1.7 on 2023-03-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=1, null=True, verbose_name='Статус активности'),
        ),
    ]
